// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5BnidjGKcuONVOEGfbilVQy1b5LxT7os',
    appId: '1:737316834637:web:b6ea7b0211fcbc2d33fb04',
    messagingSenderId: '737316834637',
    projectId: 'crypto-trading-app-de333',
    authDomain: 'crypto-trading-app-de333.firebaseapp.com',
    storageBucket: 'crypto-trading-app-de333.appspot.com',
    measurementId: 'G-0R3VC9GW94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtgToNx6FOP0WX03ibDeTB6VT7H052lb0',
    appId: '1:737316834637:android:1dd21f2992b88aa933fb04',
    messagingSenderId: '737316834637',
    projectId: 'crypto-trading-app-de333',
    storageBucket: 'crypto-trading-app-de333.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWRAzfHM9WlaXwY_Eo44AF1eyEgPT-VLo',
    appId: '1:737316834637:ios:1b77e035ad6d6aca33fb04',
    messagingSenderId: '737316834637',
    projectId: 'crypto-trading-app-de333',
    storageBucket: 'crypto-trading-app-de333.appspot.com',
    iosBundleId: 'com.example.myTradingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWRAzfHM9WlaXwY_Eo44AF1eyEgPT-VLo',
    appId: '1:737316834637:ios:52899ad9f23deedb33fb04',
    messagingSenderId: '737316834637',
    projectId: 'crypto-trading-app-de333',
    storageBucket: 'crypto-trading-app-de333.appspot.com',
    iosBundleId: 'com.example.myTradingApp.RunnerTests',
  );
}
